import streamlit
streamlit.logo("logo.jpg")
streamlit.header("Hey! I am Bhumanyu Chouhan from Jodhpur, Rajasthan, India!")
streamlit.subheader("I have created this website to introduce to my some simple, but interesting programming projects!")
streamlit.subheader("You can just use my these projects in your computer or just take reference to make your own projects!")
streamlit.markdown("1. PyManager: File manager appplication using Python's Tkinter module")
streamlit.image("Illustration_Pymanager.jpg")
streamlit.markdown("Link: https://github.com/Bhumanyu-git/pymanager")
streamlit.markdown("2. Polleroid: Voting web application using HTML, JavaScript & CSS")
streamlit.image("Illustration_Polleroid.jpg")
streamlit.markdown("Link: https://github.com/Bhumanyu-git/Polleroid")
streamlit.markdown("3. PyAssistant: Simple Desktop Assistant using Python")
streamlit.image("Illustration_PyAssistant.jpg")
streamlit.markdown("Link: https://github.com/Bhumanyu-git/PyAssistant")
streamlit.markdown("4. Melodix: Simple Media Player using HTML&CSS")
streamlit.image("Illustration_Melodix.jpg")
streamlit.markdown("Link: https://github.com/Bhumanyu-git/Melodix")